version: 2

project_name: herd

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/herd
    binary: herd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: agent462
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/agent462/herd"
    description: "Multi-host SSH command execution tool"
    license: "MIT"
    install: |
      bin.install "herd"
    test: |
      system "#{bin}/herd", "version"
